apiVersion: v1
kind: Service
metadata:
  name: simpleapp-clusterip-service
  labels:
    app: simpleapp
    version: 0.0.1
spec:
  type: ClusterIP
  selector:
    app: simpleapp
    version: 0.0.1
  ports:
  - port: 80
    targetPort: 8080
