apiVersion: v1
kind: Service
metadata:
  name: simpleapp-loadbalancer
  labels: 
    app: myapp1
spec:
  type: LoadBalancer 
  selector:
    app: simpleapp
    version: 0.0.1
  ports: 
    - port: 80
      targetPort: 8080
