apiVersion: v1
kind: Service
metadata:
  name: simpleapp-loadbalancer
  labels: 
    app: simpleapp
    version: 0.0.1
  annotations:
spec:
  type: LoadBalancer 
  loadBalancerIP: 20.79.243.96
  externalTrafficPolicy: Local
  selector:
    app: simpleapp
    version: 0.0.1
  ports:
    - port: 80
      protocol: tcp
      targetPort: 8080
      name: "http"
